"""empty message

Revision ID: 10ef3476d5d6
Revises: 8f29142e6246
Create Date: 2017-02-08 21:39:01.970000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10ef3476d5d6'
down_revision = '8f29142e6246'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('comment_id', sa.Integer(), nullable=True))
    op.add_column('notifications', sa.Column('post_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'post_id')
    op.drop_column('notifications', 'comment_id')
    ### end Alembic commands ###
