"""empty message

Revision ID: 1e203751d342
Revises: cf15f1d27f5f
Create Date: 2017-01-13 16:10:14.419000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e203751d342'
down_revision = 'cf15f1d27f5f'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knjige', sa.Column('isbn', sa.VARCHAR(length=64), nullable=True))
    op.add_column('source', sa.Column('knjizara', sa.VARCHAR(length=64), nullable=True))
    op.add_column('source', sa.Column('knjizara_sajt', sa.VARCHAR(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source', 'knjizara_sajt')
    op.drop_column('source', 'knjizara')
    op.drop_column('knjige', 'isbn')
    ### end Alembic commands ###
