"""empty message

Revision ID: 2a9f621148f8
Revises: 2cc0e18eef23
Create Date: 2016-12-12 23:45:03.014607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a9f621148f8'
down_revision = '2cc0e18eef23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('parrent_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'parrent_id')
    # ### end Alembic commands ###
