"""empty message

Revision ID: 321386ab17c9
Revises: 528d5c29cc01
Create Date: 2016-12-02 11:57:49.687000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '321386ab17c9'
down_revision = '528d5c29cc01'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('social_image', sa.String(length=265), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'social_image')
    ### end Alembic commands ###
