"""empty message

Revision ID: 385a11d9cdc9
Revises: aa6fa7c02bac
Create Date: 2016-12-05 21:57:58.957000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '385a11d9cdc9'
down_revision = 'aa6fa7c02bac'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'body_html')
    ### end Alembic commands ###
