"""empty message

Revision ID: 42f324e8531d
Revises: f23ec66e5e98
Create Date: 2016-12-01 22:11:07.653000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42f324e8531d'
down_revision = 'f23ec66e5e98'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('image', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'image')
    ### end Alembic commands ###
