"""empty message

Revision ID: 528d5c29cc01
Revises: 4f4e3e365bc0
Create Date: 2016-12-02 11:38:06.386000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '528d5c29cc01'
down_revision = '4f4e3e365bc0'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('image', sa.String(length=256), nullable=True))
    op.drop_column('user', 'images')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('images', mysql.VARCHAR(length=256), nullable=True))
    op.drop_column('user', 'image')
    ### end Alembic commands ###
