"""empty message

Revision ID: 54f686098280
Revises: e5515db86800
Create Date: 2016-11-14 19:02:26.874000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54f686098280'
down_revision = 'e5515db86800'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source', sa.Column('slika', sa.VARCHAR(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source', 'slika')
    ### end Alembic commands ###
