"""empty message

Revision ID: 87bbc8883c43
Revises: d2a39f02be43
Create Date: 2016-11-22 16:55:39.175000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87bbc8883c43'
down_revision = 'd2a39f02be43'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'confirmed')
    ### end Alembic commands ###
