"""empty message

Revision ID: 8f29142e6246
Revises: 6cc8991315a2
Create Date: 2017-02-03 15:25:09.950000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8f29142e6246'
down_revision = '6cc8991315a2'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.Integer(), nullable=True),
    sa.Column('reciver', sa.Integer(), nullable=True),
    sa.Column('type', sa.VARCHAR(length=36), nullable=True),
    sa.Column('flag', sa.VARCHAR(length=8), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reciver'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('notification')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('sender', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('reciver', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('type', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('flag', mysql.VARCHAR(length=8), nullable=True),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['reciver'], [u'user.id'], name=u'notification_ibfk_1'),
    sa.ForeignKeyConstraint(['sender'], [u'user.id'], name=u'notification_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('notifications')
    ### end Alembic commands ###
