"""empty message

Revision ID: 95eff3f3bbd8
Revises: 385a11d9cdc9
Create Date: 2016-12-09 10:09:09.242000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95eff3f3bbd8'
down_revision = '385a11d9cdc9'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follow')
    ### end Alembic commands ###
