"""empty message

Revision ID: a3cf33673797
Revises: 321386ab17c9
Create Date: 2016-12-02 13:48:27.439000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3cf33673797'
down_revision = '321386ab17c9'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar_hash')
    ### end Alembic commands ###
