"""empty message

Revision ID: ab11f3a8007e
Revises: 4e755447129e
Create Date: 2017-01-12 23:15:25.961000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab11f3a8007e'
down_revision = '4e755447129e'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knjige', sa.Column('timestamp', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knjige', 'timestamp')
    ### end Alembic commands ###
