"""empty message

Revision ID: b9935dc72898
Revises: 930871b8c7cd
Create Date: 2017-01-07 20:59:24.028000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9935dc72898'
down_revision = '930871b8c7cd'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('book_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'post', 'knjige', ['book_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'book_id')
    ### end Alembic commands ###
