"""empty message

Revision ID: cf15f1d27f5f
Revises: ab11f3a8007e
Create Date: 2017-01-13 15:58:18.113000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf15f1d27f5f'
down_revision = 'ab11f3a8007e'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'knjige', 'authors', ['autor'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'knjige', type_='foreignkey')
    ### end Alembic commands ###
