"""empty message

Revision ID: f23ec66e5e98
Revises: 05992c958f40
Create Date: 2016-11-30 12:28:55.382000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f23ec66e5e98'
down_revision = '05992c958f40'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('member_since', sa.DateTime(), nullable=True))
    op.drop_column('user', 'member_sience')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('member_sience', mysql.DATETIME(), nullable=True))
    op.drop_column('user', 'member_since')
    ### end Alembic commands ###
